const assert=require('node:assert/strict');
const C=require('./engine.js');
const A=require('./accuracy.js');
const t4={type:'T4',year:'2025',province:'ON',confirmed:true,fields:{16:'4034.10','16A':'396',18:'1077.48',24:'65700',26:'81200',50:'0123456'}};
assert(!C.check(t4).some(x=>x.status==='mismatch'));
assert(C.check({...t4,fields:{...t4.fields,18:'1100'}}).some(x=>x.title==='EI annual ceiling'&&x.status==='review'));
assert(C.check({...t4,confirmed:false}).every(x=>x.status!=='pass'));
assert(C.check({...t4,province:'QC'}).some(x=>x.title==='Quebec contribution rules'));
assert(C.check({type:'Paystub',confirmed:true,fields:{gross:'2000',deductions:'500',net:'1500'}}).some(x=>x.title==='Current gross-to-net'&&x.status==='pass'));
assert(C.check({type:'T1',confirmed:true,fields:{15000:'100000',23300:'5000',23400:'95000',23500:'0',23600:'95000',25700:'2000',26000:'93000'}}).filter(x=>x.status==='pass').length===3);
assert(C.check({type:'T2',confirmed:true,fields:{300:'100000',deductions:'20000',360:'80000'}}).some(x=>x.status==='pass'));
assert(C.amount('')===null);assert(Number.isNaN(C.amount('abc')));assert(C.amount('(1,234.56)')===-1234.56);
const r=[{y:100,text:'14 100000.00',items:[{str:'14',x:350},{str:'100000.00',x:415}]}];assert.equal(C.candidates(r,'T4')['14'][0].value,'100000.00');
console.log('Contribution, arithmetic, missing-input, format, confirmation and extraction checks passed.');
const L=require('./layout.js');
const item=(str,x,y,width=45)=>({str,x,y,width,height:10});
const page=items=>({width:612,height:792,rotation:0,method:'PDF text',rows:[{y:100,items}]});
const reference=page([item('100.00',100,100),item('EXAMPLE',200,100,60)]);
assert.equal(L.inspect(reference,2,reference).issues.length,0);
const moved=page([item('100.00',106,105),item('EXAMPLE',194,96,60)]);
assert.equal(L.inspect(moved,2,reference).issues.filter(x=>x.status==='review').length,2);
assert.equal(L.inspect(moved,8,reference).issues.length,0);
assert(L.inspect(page([item('100.00',100,100),item('200.00',200,106)])).issues.length===2);
assert(L.inspect(page([item('100.00',100,100),item('200.00',100,80),item('300.00',100,60),item('400.00',107,40)])).issues.some(x=>x.detail.includes('column')));
assert(L.inspect({...reference,method:'OCR'}).checked===0);
assert(L.inspect({...reference,width:600},2,reference).checked===0);
console.log('Alignment shifts, tolerance, row/column outliers, reference matching and scan safeguards passed.');
const navigationDoc={type:'T4',pages:[page([item('14',10,100)]),page([item('1077.48',100,100)])],candidates:{18:[{page:2,value:'1077.48'}]}};
assert.equal(L.locateFinding(navigationDoc,{title:'EI premium arithmetic'},0).page,1);
assert.equal(L.locateFinding(navigationDoc,{title:'EI premium arithmetic'},0).rects.length,1);
assert.equal(L.locateFinding(navigationDoc,{title:'General review'},1).page,1);
assert(L.locateFinding(navigationDoc,{title:'General review'},1).note.includes('no precise text location'));
assert.equal(L.locateFinding(navigationDoc,{title:'Text alignment',page:2,rect:{x:10,y:20,width:30,height:10}},0).page,1);
console.log('Finding navigation, page selection, targeted regions and no-location fallback passed.');

// Regression cases from the October 1 audit: each previously gave a wrong pass,
// lost an input, or pointed at an unrelated source value.
for(const value of ['1,2.00','100)','(100','(-100.00)','1,,000.00','12 34.00','1e3','1.234'])assert(Number.isNaN(C.amount(value)),value);
assert.equal(C.amount('1,234,567.89'),1234567.89);
assert.equal(C.amount('1 234.56'),1234.56);
assert.equal(C.amount('-$1,234.56'),-1234.56);
const negative=C.check({...t4,fields:{16:'-10'}});
assert(negative.some(r=>r.status==='mismatch'&&r.fieldKeys.includes('16')));
assert(!negative.some(r=>r.title==='CPP annual ceiling'&&r.status==='pass'));
assert.notEqual(C.normal('李 小明'),C.normal('張 偉'));
assert.notEqual(C.normal('Ann Ab'),C.normal('Anna B'));
assert.equal(C.normal(undefined),'');assert.equal(C.normal(null),'');
assert(C.check({type:'Paystub',confirmed:true,fields:{},name:'張 偉',expectedName:'李 小明'}).some(r=>r.title==='Name against reference'&&r.status==='review'));
const missing=C.check({type:'Paystub',confirmed:true,fields:{},expectedName:'Example Worker',expectedAddress:'100 Example Street',name:'',address:''});
assert(missing.some(r=>r.title==='Name against reference'&&r.status==='review'));
assert(missing.some(r=>r.title==='Address against reference'&&r.status==='review'));
const penny=C.check({type:'Paystub',confirmed:true,fields:{gross:'2000',deductions:'500',net:'1500.01'}});
assert(penny.some(r=>r.title==='Current gross-to-net'&&r.status==='mismatch'));
assert(C.check({type:'T1',confirmed:true,fields:{43500:'1000',48200:'1500',48400:'500',48500:'500'}}).some(r=>r.title==='Balance owing'&&r.status==='mismatch'));
assert.equal(C.detect('Gross Pay 15000.00\nNet Pay 12000.00','payment.pdf'),'Paystub');
assert.equal(C.detect('Income Tax and Benefit Return','T4 mislabeled.pdf'),'T1');
assert.equal(C.detectYear('Tax year 2025\nPrinted 2026','T4 2026.pdf'),'');
assert.equal(C.detectYear('Pay period 2026-01-01 to 2026-01-14','stub.pdf'),'2026');
assert.equal(C.detectYear('2024 and 2025','T4 2026.pdf'),'');
assert.equal(C.detectYear('No year given','T4_2025.pdf'),'');
assert.equal(C.detectYear('Gross Pay 2000.00\nPay period 2026-09-06 to 2026-09-19','stub.pdf'),'2026');
assert.equal(C.detectYear('T4\n14 2025.00','T4 2024.pdf'),'');
assert.equal(C.candidateKey('14','1,000.00'),C.candidateKey('14','1000.00'));
assert.notEqual(C.candidateKey('50','0123456'),C.candidateKey('50','123456'));
const partial=C.check({type:'T4',year:'2025',province:'ON',confirmed:true,cppMonths:'2',fields:{16:'672.35','16A':'30.05',26:'12634.65'}});
assert(partial.some(r=>r.title==='CPP2 arithmetic'&&r.status==='review'&&r.calculation.difference===0));
assert(!partial.some(r=>r.status==='mismatch'));
assert(C.check({...t4,cppMonths:''}).some(r=>r.title==='CPP2 arithmetic'&&r.status==='review'));
assert(C.check({...t4,cppMonths:'13'}).some(r=>r.title==='CPP pensionable months'&&r.status==='mismatch'));
assert(C.check({type:'T4',year:'2026',province:'ON',confirmed:true,cppMonths:'12',fields:{16:'4230.45','16A':'416',18:'1123.07',24:'68900',26:'85000'}}).every(r=>r.status!=='mismatch'));
const ytdRow={y:100,text:'YTD Gross Pay 20,000.00',items:[item('YTD Gross Pay',10,100),item('20,000.00',200,100)]};
assert.equal(C.candidates([ytdRow],'Paystub').ytdGross[0].value,'20,000.00');
assert(!C.candidates([ytdRow],'Paystub').gross);
assert.equal(C.candidates([{y:100,text:'300 (1,234.56)',items:[item('300',10,100),item('(1,234.56)',200,100)]}],'T2')['300'][0].value,'(1,234.56)');
const regionDoc={type:'T4',pages:[page([item('50.00',50,100),item('50.00',400,100)])],candidates:{18:[{page:1,value:'50.00',rect:{x:50,y:100,width:45,height:10}}]}};
const located=L.locateFinding(regionDoc,{title:'EI annual ceiling'},0);
assert.equal(located.rects.length,1);
assert.equal(located.rects[0].x,50);
const unicodeDoc={type:'T4',name:'李 小明',pages:[page([item('李',10,100),item('小明',50,100),item('UNRELATED',200,100)])],candidates:{}};
assert.equal(L.locateFinding(unicodeDoc,{title:'Name against reference'},0).rects.length,2);
assert.equal(L.inspect({...reference,cropBox:[0,0,612,792]},2,{...reference,cropBox:[10,0,622,792]}).checked,0);
const html=require('node:fs').readFileSync(require('node:path').join(__dirname,'index.html'),'utf8');
for(const province of ['ON','BC','AB','SK','MB','NB','NS','PE','NL','QC','YT','NT','NU'])assert(html.includes('<option value="'+province+'">'+province+'</option>'));
console.log('Audit regression checks passed: strict amounts, negative deductions, one-cent math, Unicode/missing identities, classification/year, part-year CPP2, 2026 caps, YTD extraction, source regions, crop origins and province options.');

assert(C.check({...t4,fields:{24:'65700.01'}}).some(r=>r.title==='EI earnings ceiling'&&r.status==='mismatch'));
// Applicant reference and cross-document reconciliation use fictional records.
const makeRow=(text,y=100,parts)=>({text,y,items:parts||[item(text,40,y,Math.max(60,text.length*5))]});
const idPage={method:'PDF text',text:'Fictional identification',rows:[makeRow('Full name: EXAMPLE ALEX',700),makeRow('Address: 123 EXAMPLE STREET',680),makeRow('OTTAWA ON K1A 0B1',660)]};
const identity=C.identity([idPage],'ID');assert.equal(identity.name,'EXAMPLE ALEX');assert.equal(identity.address,'123 EXAMPLE STREET, OTTAWA ON K1A 0B1');assert(identity.regions.name[0].page===1);
assert.deepEqual(C.candidates(idPage.rows,'ID'),{});
assert.equal(C.addressKey('123 Example St, Ottawa Ontario K1A0B1'),C.addressKey(identity.address));
assert.notEqual(C.addressKey('124 Example St Ottawa ON K1A 0B1'),C.addressKey(identity.address));
assert.equal(C.detect('Corporation notice of assessment','file.pdf'),'CNOA');
assert.equal(C.detect('Notice of assessment\nBusiness number: 123456789RC0001','fictional.pdf'),'CNOA');
assert.equal(C.detect('Notice of reassessment\nTax year 2025','T1.pdf'),'NOA');
assert.equal(C.validDate('2025-02-30'),false);assert.equal(C.validDate('2024-02-29'),true);
const assessedRow=makeRow('15000 Total income 100,000.00',100,[item('15000',40,100),item('Total income',100,100,100),item('100,000.00',350,100)]);
assert.equal(C.candidates([assessedRow],'NOA')['15000'][0].value,'100,000.00');
assert(C.candidates([makeRow('15000 Total income 100,000.00')],'NOA')['15000'][0].rect);
const labelledRow=makeRow('Taxable income: 80,000.00',100,[item('Taxable income:',40,100,110),item('80,000.00',350,100)]);
assert.equal(C.candidates([labelledRow],'CNOA')['360'][0].value,'80,000.00');
const columnRows=[makeRow('Current YTD',150,[item('Current',220,150),item('YTD',350,150)]),makeRow('CPP 10.00 100.00',100,[item('CPP',40,100),item('10.00',220,100),item('100.00',350,100)])];
assert.equal(C.candidates(columnRows,'Paystub').cpp[0].value,'10.00');assert.equal(C.candidates(columnRows,'Paystub').ytdCpp[0].value,'100.00');
assert.equal(C.candidates([makeRow('YTD CPP2 30.05')],'Paystub').ytdCpp2[0].value,'30.05');
const basic={year:'2025',name:'EXAMPLE ALEX',address:identity.address,confirmed:true,version:'original',pages:[idPage]};
const personal=[{...basic,type:'ID',file:'Fictional ID',fields:{},identityRegions:identity.regions},{...basic,type:'NOA',file:'Fictional NOA',version:'assessment',fields:{15000:'100000',23600:'95000',26000:'93000'}},{...basic,type:'T1',file:'Fictional T1',fields:{15000:'100000',23600:'95000',26000:'92000'}}];
const ref={name:basic.name,address:basic.address,confirmed:true,file:'Fictional ID',sourceIndex:0};
const taxBatch=C.batch(personal,ref);
assert(taxBatch.some(r=>r.title==='Line 15000 — NOA ↔ T1'&&r.status==='pass'));
assert(taxBatch.some(r=>r.title==='Line 26000 — NOA ↔ T1'&&r.status==='review'&&r.detail.includes('$1,000.00')));
assert(taxBatch.find(r=>r.title==='Line 26000 — NOA ↔ T1').targets.every(t=>t.fieldKeys[0]==='26000'));
assert(C.batch([{...personal[1],name:'EXAMPLE BLAKE'}],ref).some(r=>r.title.startsWith('Name / spelling')&&r.status==='mismatch'&&r.targets[1].docIndex===0));
assert(C.batch(personal.map(d=>({...d,confirmed:false})),{...ref,confirmed:false}).every(r=>r.status!=='pass'));
assert(C.batch([{...personal[1],name:'EXAMPLE BLAKE'}],{...ref,confirmed:false}).filter(r=>r.title.startsWith('Name / spelling')).every(r=>r.status==='review'));
assert(C.batch([personal[1],{...personal[2],year:'2024'}],ref).filter(r=>r.title.includes('NOA ↔ T1')).every(r=>r.status!=='pass'));
const corps=[{...basic,type:'CNOA',file:'Fictional CNOA',name:'EXAMPLE CORP',fiscalStart:'2024-07-01',fiscalEnd:'2025-06-30',version:'assessment',fields:{360:'80000'}},{...basic,type:'T2',file:'Fictional T2',name:'EXAMPLE CORP',fiscalStart:'2024-07-01',fiscalEnd:'2025-06-30',fields:{360:'80000'}}];
const corpBatch=C.batch(corps,ref);assert(corpBatch.some(r=>r.title==='Line 360 — CNOA ↔ T2'&&r.status==='pass'));
assert(!corpBatch.some(r=>r.title.includes('Name / spelling')&&r.status==='mismatch')); // personal ID is not a corporation reference
assert(C.batch([corps[0],{...corps[1],fiscalStart:'2025-01-01'}],ref).filter(r=>r.title.includes('CNOA ↔ T2')).every(r=>r.status!=='pass'));
assert(C.batch([corps[0],{...corps[1],year:'2024'}],ref).filter(r=>r.title.includes('CNOA ↔ T2')).every(r=>r.status!=='pass'));
const slip={...basic,type:'T4',file:'Fictional T4',employer:'EXAMPLE EMPLOYER',fields:{14:'100000',22:'23000',16:'4034.10','16A':'396',18:'1077.48',20:'2000'}};
const stub={...basic,type:'Paystub',file:'Fictional final paystub',employer:'EXAMPLE EMPLOYER',payStart:'2025-12-15',payEnd:'2025-12-28',payDate:'2025-12-31',finalPaystub:true,fields:{ytdTaxableGross:'100000',ytdIncomeTax:'23000',ytdCpp:'4034.10',ytdCpp2:'396',ytdEi:'1077.48',ytdRpp:'2000'}};
assert(C.batch([slip,stub],ref).filter(r=>r.title.includes('T4 ↔ paystub')).every(r=>r.status==='pass'));
assert(C.batch([slip,{...stub,finalPaystub:false}],ref).filter(r=>r.title.includes('T4 ↔ paystub')).every(r=>r.status!=='pass'));
assert(C.batch([slip,{...stub,employer:'OTHER EMPLOYER'}],ref).filter(r=>r.title.includes('T4 ↔ paystub')).every(r=>r.status!=='pass'));
assert(C.batch([{...slip,employer:undefined},{...stub,employer:undefined}],ref).filter(r=>r.title.includes('T4 ↔ paystub')).every(r=>r.status!=='pass'));
assert(C.batch([{...slip,fields:{16:'-10'}},{...stub,fields:{ytdCpp:'-10'}}],ref).some(r=>r.title==='CPP — T4 ↔ paystub'&&r.status==='review'));
assert(C.batch([slip,{...stub,fields:{ytdGross:'100000'}}],ref).some(r=>r.title==='Employment income — T4 ↔ paystub'&&r.status==='review'));
assert(C.batch([slip,{...stub,fields:{ytdGross:'100000'},taxableBasisConfirmed:true}],ref).some(r=>r.title==='Employment income — T4 ↔ paystub'&&r.status==='pass'));
const previous={...stub,file:'Fictional previous stub',payStart:'2025-12-01',payEnd:'2025-12-14',payDate:'2025-12-17',finalPaystub:false,fields:{ytdGross:'96000',ytdDeductions:'24000',ytdNet:'72000'}};
const next={...stub,fields:{gross:'4000',deductions:'1000',net:'3000',ytdGross:'100000',ytdDeductions:'25000',ytdNet:'75000'}};
assert.equal(C.batch([previous,next],ref).filter(r=>r.title.startsWith('YTD continuity')&&r.status==='pass').length,3);
assert(C.batch([previous,{...next,payStart:'2025-12-20'}],ref).filter(r=>r.title.startsWith('YTD continuity')).every(r=>r.status==='review'));
assert(C.batch([personal[1],personal[2],{...personal[2],file:'Fictional duplicate T1'}],ref).some(r=>r.title==='Duplicate or competing records'));
assert(C.batch([personal[1],personal[2],{...personal[2],file:'Fictional old T1',version:'superseded'}],ref).some(r=>r.title==='Line 15000 — NOA ↔ T1'&&r.status==='pass'));
const custom='custom:RRSP LIMIT';assert(C.batch([{...personal[1],labels:{[custom]:'RRSP limit'},fields:{[custom]:'5000'}},{...personal[2],labels:{[custom]:'RRSP limit'},fields:{[custom]:'5001'}}],ref).some(r=>r.title==='RRSP limit — NOA ↔ T1'&&r.status==='review'));
assert(C.batch([{...slip,labels:{'custom:UNION DUES':'Union dues'},fields:{'custom:UNION DUES':'100'}},{...stub,labels:{'custom:UNION DUES':'Union dues'},fields:{'custom:UNION DUES':'100'}}],ref).some(r=>r.title==='Union dues — T4 ↔ paystub'&&r.status==='pass'));
assert(L.locateFinding({type:'ID',pages:[idPage],identityRegions:identity.regions},{title:'Name / spelling',identityKey:'name'},0).rects.length>0);
assert.equal(L.locateFinding({type:'T1',pages:[idPage]},{title:'Other amounts',page:1,rects:[{x:1,y:2,width:3,height:4},{x:5,y:6,width:7,height:8}]},0).rects.length,2);
assert(C.check({type:'NOA',confirmed:true,fields:{43500:'1000',48200:'1500',assessmentBalance:'-500'}}).some(r=>r.title==='Balance from this assessment'&&r.status==='pass'));
assert(C.check({type:'NOA',confirmed:true,fields:{43500:'1000',48200:'1500',assessmentBalance:'-450'}}).some(r=>r.title==='Balance from this assessment'&&r.status==='review'&&r.detail.includes('interest')&&!r.detail.includes('Annual-rate')));
console.log('Applicant ID, notice extraction, current/YTD columns, matching periods, corporate separation, final-paystub basis, duplicate/superseded records, custom amounts, source targets and batch confirmation checks passed.');
// The accuracy workflow must expose incomplete coverage, scoped conclusions and private evidence.
const reviewedPage={...idPage,rendered:true,review:{status:'reviewed',note:'Fictional page inspected at readable zoom, including every populated area and relevant blank.'}};
const reviewStub={...basic,type:'Paystub',file:'Fictional accuracy stub',fields:{gross:'2000.00',deductions:'500.00',net:'1500.01'},pages:[reviewedPage]};
const accuracy=A.build([reviewStub],ref);
assert.equal(accuracy.coverage.visuallyReviewed,1);assert.match(accuracy.coverage.conclusion,/incomplete/);
const mathError=accuracy.findings.find(r=>r.title==='Current gross-to-net');assert.equal(mathError.status,'Error');assert.equal(mathError.calculation.expected,1500);assert.equal(mathError.calculation.difference,.01);assert.match(mathError.calculation.formula,/gross − deductions/);
assert.equal(accuracy.fieldLedger.find(r=>r.field==='net').status,'Error');assert.equal(accuracy.fieldLedger.find(r=>r.field==='hours').status,'Not verifiable');
assert.equal(A.build([{...reviewStub,confirmed:false}],ref).findings.find(r=>r.title==='Current gross-to-net').status,'Needs confirmation');
const correct={...reviewStub,fields:{gross:'2000.00',deductions:'500.00',net:'1500.00'}};
assert.equal(A.build([correct],ref).findings.find(r=>r.title==='Current gross-to-net').status,'Verified');
assert.equal(A.build([{...t4,pages:[reviewedPage]}]).findings.find(r=>r.title==='CPP annual ceiling').status,'Internally consistent');
assert.equal(A.build([{...correct,pages:[{...reviewedPage,rendered:false}]}]).coverage.visuallyReviewed,0);
assert.equal(A.build([{...correct,pages:[{...reviewedPage,review:{status:'unreadable',note:'Numbers are clipped.'}}]}]).coverage.unreadable,1);
assert.equal(A.build([{...correct,pages:[reviewedPage,{...idPage}]}]).coverage.unreviewed,1);
assert(A.build([{...correct,pages:[reviewedPage,{...reviewedPage}]}]).findings.some(r=>r.title==='Possible duplicate page'));
assert(A.build([{...correct,pages:[{...reviewedPage,text:'Page 1 of 2'}]}]).findings.some(r=>r.title==='Printed page / PDF page count'));
assert.equal(A.build(personal,ref).findings.find(r=>r.title==='Line 15000 — NOA ↔ T1').status,'Internally consistent');
const assessedDifference=A.build(personal,ref).findings.find(r=>r.title==='Line 26000 — NOA ↔ T1');assert.equal(assessedDifference.status,'Needs confirmation');assert.equal(assessedDifference.calculation.difference,-1000);
correct.accuracyReviews={withholding:{status:'Not applicable',severity:'Major',note:'Fictional test only: no withholding review requested.',basis:A.basis([correct],ref)}};
assert.equal(A.build([correct],ref).findings.find(r=>r.title==='Exact payroll deductions and eligibility').status,'Not applicable');
assert.equal(A.build([correct],{...ref,address:'Changed source address'}).findings.find(r=>r.title==='Exact payroll deductions and eligibility').status,'Not verifiable');
assert.match(A.build([correct],{...ref,address:'Changed source address'}).findings.find(r=>r.title==='Exact payroll deductions and eligibility').detail,/stale/);
const privateReport=A.build([{...correct,name:'<script>alert(1)</script>',pages:[{...reviewedPage,formFields:[{name:'Driver licence',value:'TEST-ID-PRIVATE',visible:'',rect:{x:40,y:100,width:50,height:10}}],rows:[makeRow('SIN: 123 456 789')]}]}]);
const printable=A.html(privateReport);assert(!printable.includes('<script>'));assert(printable.includes('&lt;script&gt;'));assert(!printable.includes('123 456 789'));assert(!printable.includes('TEST-ID-PRIVATE'));assert(printable.includes('Complete field ledger'));assert(printable.includes('Print / Save as PDF'));
assert.equal(C.check({type:'Paystub',confirmed:true,fields:{gross:'.30',deductions:'.10',net:'.20'}}).filter(r=>r.status==='pass').length,0); // Strict formatting remains deliberate.
assert(C.check({type:'Paystub',confirmed:true,fields:{hours:'0.07',rate:'0.50',regular:'0.04'}}).some(r=>r.title==='Regular earnings'&&r.status==='pass'));
assert(Number.isNaN(C.amount('100000000000000000.01')));
assert(A.mask('NETFILE access code AB1CD2EF').includes('[masked identifier]'));
assert.equal(A.build([{...correct,labels:{'custom:SIN':'SIN'},fields:{'custom:SIN':'1234'}}]).fieldLedger.find(r=>r.field==='custom:SIN').enteredValue,'[masked identifier]');
assert(A.build([{...correct,pages:[{...reviewedPage,formFields:[{name:'Net pay',value:'1500.00',visible:'1500.01',rect:{x:1,y:2,width:3,height:4}}]}]}]).findings.some(r=>r.title==='PDF form value / appearance difference'));
assert(A.build([{...correct,payStart:'2025-12-20',payEnd:'2025-12-01'}]).findings.some(r=>r.status==='Error'&&r.title==='Period start is after period end'));
const changedName=A.build([{...correct,name:'EXAMPLE BLAKE',sourceIdentity:{name:'EXAMPLE ALEX'},identityRegions:identity.regions}]).fieldLedger.find(r=>r.field==='name');assert.equal(changedName.status,'Needs confirmation');assert.match(changedName.displayed,/EXAMPLE ALEX/);assert.equal(changedName.enteredValue,'EXAMPLE BLAKE');
assert(C.check({...t4,province:'XX'}).every(r=>!r.title.includes('annual ceiling')));
assert.equal(C.candidates([makeRow('Total deductions from lines 311–352: 20000.00')],'T2').deductions[0].value,'20000.00');
console.log('Accuracy coverage, exact-cent evidence, six statuses, no unsupported verification, stale review invalidation, print escaping and identifier masking checks passed.');
// Controlled I/O tests exercise the real load/clear handlers without a browser or CDN.
async function ioChecks(){
 const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),elements=new Map();
 const element=()=>({value:'',files:[],textContent:'',disabled:false,checked:false,children:[],click(){},scrollIntoView(){},addEventListener(){},replaceChildren(...v){this.children=v;},append(...v){this.children.push(...v);}});
 const context=vm.createContext({window:{Checker:C,Accuracy:A,addEventListener(){}},LayoutChecker:L,document:{getElementById(id){if(!elements.has(id))elements.set(id,element());return elements.get(id);},createElement:element},TextDecoder,Uint8Array,crypto:require('node:crypto').webcrypto,console,Promise});
 vm.runInContext(fs.readFileSync(path.join(__dirname,'app.js'),'utf8')+'\nshow=()=>{};results=()=>{};preview=async()=>{};',context);
 const run=code=>vm.runInContext(code,context),input={name:'fictional.pdf',size:5,arrayBuffer:async()=>new TextEncoder().encode('%PDF-').buffer};context.input=input;
 context.unmappedDoc={type:'T2',confirmed:true,fields:{},candidates:{},pages:[{...page([]),rows:[makeRow('Other charge: 12.34')]}]};
 assert(run('findings(unmappedDoc)').some(r=>r.title.includes('Other amounts to review')&&r.rects.length===1));
 let destroyed=0;context.fakePdf={numPages:41,destroy:async()=>{destroyed++;}};
 run('openPdf=async()=>fakePdf');await run('upload([input])');assert.equal(destroyed,1);
 context.fakePdf={numPages:1,getPage:async()=>{throw Error('Page failed');},destroy:async()=>{destroyed++;}};
 await run('upload([input])');assert.equal(destroyed,2);
 const fakePage={view:[0,0,612,792],rotate:0,getTextContent:async()=>({items:[]})};
 context.fakePdf={numPages:1,getPage:async()=>fakePage,destroy:async()=>{destroyed++;}};
 run('ocr=async()=>{throw Error("OCR offline");}');await run('upload([input])');
 assert.equal(run('docs.length'),1);assert(run('docs[0].pages[0].method').startsWith('OCR unavailable'));
 assert.equal(run('docs[0].province'),'');
 let exportBlob;context.Blob=Blob;context.URL={createObjectURL(blob){exportBlob=blob;return 'blob:fictional';},revokeObjectURL(){}};
 run('$("export").onclick()');const exported=JSON.parse(await exportBlob.text());
 assert.equal(exported.type,'Unknown');assert.equal(exported.inputsConfirmed,false);assert.equal(exported.fields.gross,undefined);assert(Array.isArray(exported.checks));
 assert.equal(exported.schemaVersion,3);assert.equal(exported.sha256,require('node:crypto').createHash('sha256').update('%PDF-').digest('hex'));
 assert.equal(exported.documents[0].sha256,exported.sha256);assert.equal(exported.accuracyReview.documents[0].sha256,exported.sha256);
 assert.equal(exported.documents[0].pages[0].previewRendered,false);assert.equal(exported.documents[0].pages[0].alignment.execution,'blocked');
 assert.equal(exported.accuracyReview.documents[0].pages[0].alignment.execution,'blocked');
 assert.equal(exported.documents.length,1);assert.equal(exported.documents[0].pages.length,1);assert(Array.isArray(exported.crossDocumentChecks));assert.equal(exported.applicantReference.confirmed,false);
 const target=run('docs[0]');target.reference={name:'old',pages:[]};elements.get('referencePdf').files=[input];
 assert(run('findings(docs[0])').some(r=>r.title.includes('alignment not performed')));
 run('openPdf=async()=>{throw Error("Bad reference");}');await run('$("referencePdf").onchange()');
 assert.equal(target.reference,null);assert.equal(elements.get('referencePdf').disabled,false);
 let release;context.waitingPdf=new Promise(resolve=>{release=resolve;});context.fakePdf={numPages:1,getPage:async()=>fakePage,destroy:async()=>{destroyed++;}};
 run('openPdf=async()=>waitingPdf');elements.get('referencePdf').files=[input];const pending=run('$("referencePdf").onchange()');
 run('$("clearReference").onclick()');release(context.fakePdf);await pending;assert.equal(target.reference,null);
 assert.equal(elements.get('referenceStatus').textContent,'No reference PDF selected.');
 context.waitingPdf=new Promise(resolve=>{release=resolve;});elements.get('referencePdf').files=[input];const pendingClear=run('$("referencePdf").onchange()');
 await run('$("clear").onclick()');release(context.fakePdf);await pendingClear;
 assert.equal(run('docs.length'),0);assert.equal(elements.get('referencePdf').disabled,false);
 context.missingReferenceDoc={type:'T4',name:'EXAMPLE',confirmed:true,fields:{},candidates:{},pages:[page([item('100.00',100,100)])],reference:{name:'Fictional reference',pages:[reference]}};
 context.mockCanvas={getContext:()=>({fillRect(){},strokeRect(){}}),setAttribute(){}};context.mockViewport={convertToViewportRectangle:x=>x};
 run('$("overlays").checked=true;drawOverlays(missingReferenceDoc,0,mockViewport,mockCanvas)');
 context.bigPage={getViewport({scale}){return{scale,width:100000*scale,height:100000*scale};}};
 const v=run('viewport(bigPage,1.6)');assert(v.width<=4096&&v.height<=4096&&v.width*v.height<=16777216);
 context.bundleFixtures=personal.map(d=>({...d,pdf:null}));
 run('docs=bundleFixtures;active=2;applicantSource=docs[0];$("expectedName").value=docs[0].name;$("expectedAddress").value=docs[0].address;$("referenceConfirmed").checked=true;');
 run('$("export").onclick()');const bundleExport=JSON.parse(await exportBlob.text());
 assert.equal(bundleExport.documents.length,3);assert.equal(bundleExport.applicantReference.sourceIndex,0);
 assert.equal(bundleExport.accuracyReview.coverage.files,3);assert.equal(bundleExport.accuracyReview.coverage.pages,3);assert(bundleExport.accuracyReview.fieldLedger.length>0);
 run('$('+'"reportHTML"'+').onclick()');const htmlExport=await exportBlob.text();assert(htmlExport.startsWith('<!doctype html>'));assert(htmlExport.includes('Complete field ledger'));
 assert(bundleExport.crossDocumentChecks.some(r=>r.title==='Line 26000 — NOA ↔ T1'&&r.targets[1].docIndex===2));
 await run('focusFinding({title:"Batch source",docIndex:1,fieldKeys:["26000"]})');assert.equal(run('active'),1);
 run('$("clearApplicant").onclick()');assert.equal(run('applicantSource'),null);assert.equal(elements.get('expectedName').value,'');assert.equal(elements.get('referenceConfirmed').checked,false);
 await run('$("clear").onclick()');assert.equal(run('docs.length'),0);
 fakePage.getAnnotations=async()=>[{subtype:'Widget',fieldName:'Net pay canonical',fieldValue:'3000.00',rect:[10,10,100,30]}];
 run('openPdf=async()=>fakePdf');await run('upload([input])');assert.equal(run('docs[0].pages[0].formFields[0].value'),'3000.00');
 run('$("pageReviewStatus").value="reviewed";$("pageReviewNote").value="Rendered page inspected.";$("savePageReview").onclick()');assert.match(elements.get('status').textContent,/Render and inspect/);
 run('docs[0].pages[0].rendered=true');run('$("savePageReview").onclick()');assert.equal(run('docs[0].pages[0].review.status'),'reviewed');
 fakePage.getAnnotations=async()=>{throw Error('Malformed widget');};await run('upload([input])');assert.match(run('docs[1].pages[0].formReadError'),/Malformed widget/);
 await run('$("clear").onclick()');assert.equal(run('docs.length'),0);
 console.log('PDF cleanup, OCR fallback, review JSON, reference replacement/removal/clear races and preview-size checks passed.');
}
ioChecks().catch(e=>{console.error(e);process.exitCode=1;});


// Preserved latest-main regressions after conflict resolution.
{
// Regressions: no silent number coercion, rounding tolerance or unsupported classification.
for(const value of ['1,23.45','12,34,567.89','1 2.00','(12.00','12.00)','(-12.00)','--12','1e3','Infinity','900719925474099.99']) assert(Number.isNaN(C.amount(value)),value);
assert.equal(C.amount('$ 1,234.50'),1234.5);
assert.equal(C.amount('(1 234.50)'),-1234.5);
assert.equal(C.cents('0.29'),29);
assert.equal(C.detect('Unrelated invoice'), 'Unknown');
assert.equal(C.detect('T4 and T1 supporting package'), 'Unknown');
assert.equal(C.detect('Statement of Remuneration Paid'), 'T4');
assert.equal(C.detectYear('Tax year 2025; issued 2026'), '');
assert.equal(C.detectYear('Tax year 2025'), '2025');
assert.equal(C.normal('JOSE'), 'JOSE');
assert.notEqual(C.normal('JOS�'),C.normal('JOS'));
const pay=fields=>C.check({type:'Paystub',confirmed:true,fields});
assert(pay({gross:'1.00',deductions:'0.00',net:'0.99'}).some(r=>r.title==='Current gross-to-net'&&r.status==='mismatch'));
assert(pay({gross:'1.00',deductions:'0.71',net:'0.29'}).some(r=>r.title==='Current gross-to-net'&&r.status==='pass'));
assert(pay({hours:'1.50',rate:'1.01',regular:'1.52'}).some(r=>r.title==='Regular earnings'&&r.status==='pass'));
assert(pay({hours:'-1.50',rate:'1.01',regular:'-1.52'}).some(r=>r.title==='Regular earnings'&&r.status==='pass'));
assert(pay({gross:'abc',deductions:'0',net:'0'}).some(r=>r.title==='Current gross-to-net'&&r.status==='review'));
assert(C.check({...t4,fields:{...t4.fields,16:'-1'}}).some(r=>r.title==='CPP annual ceiling'&&r.status==='mismatch'));
assert(C.check({...t4,province:'XX'}).every(r=>!r.title.endsWith('annual ceiling')));
assert(C.check({...t4,confirmed:false,fields:{18:'bad'}}).every(r=>r.status==='review'));
assert(C.check(t4).filter(r=>['EI premium arithmetic','CPP2 arithmetic','CPP at maximum earnings'].includes(r.title)).every(r=>r.status==='review'));
assert(C.check({type:'Unknown',confirmed:true,fields:{}}).some(r=>r.title==='Document type required'));
assert(C.check({type:'T1',confirmed:true,fields:{43500:'100',48200:'120',48400:'20',48500:'5'}}).some(r=>r.title==='Refund/balance contradiction'&&r.status==='mismatch'));
assert(C.check({type:'T1',confirmed:true,fields:{}}).some(r=>r.title==='Refund or balance'));
assert(C.check({type:'T1',confirmed:true,fields:{},expectedName:'EXAMPLE',name:''}).some(r=>r.title==='Name against reference'&&r.status==='review'));
assert.equal(L.inspect(reference,NaN).execution,'blocked');
assert.equal(L.inspect({...reference,view:[10,0,622,792]},2,reference).execution,'blocked');
assert(L.inspect(page([item('123.00',600,100,40)])).issues.some(r=>r.detail.includes('crop')));
assert.equal(L.inspect({...reference,method:'OCR'}).execution,'blocked');
assert.equal(L.inspect(page([])).execution,'blocked');
const missing=L.inspect(page([item('100.00',100,100)]),2,reference).issues.find(r=>r.title==='Reference region missing');
assert(missing && !missing.rect);
assert.equal(L.locateFinding(navigationDoc,{title:'General review',page:99},0).page,1);
assert.equal(L.locateFinding({type:'T4',name:'EXAMPLE',pages:[page([item('---',10,10)])]},{title:'Name against reference'},0).rects.length,0);
console.log('Strict amounts, exact cents, half-cent rounding, unsupported inputs, conditional rules, audit gaps and safe geometry regressions passed.');

assert.equal(C.cents('90071992547409.91'),Number.MAX_SAFE_INTEGER);
assert(Number.isNaN(C.cents('90071992547409.92')));
assert(C.check({...t4,year:'__proto__'}).some(r=>r.title==='Year-specific contribution rules'));
const mainHtml=require('node:fs').readFileSync(require('node:path').join(__dirname,'index.html'),'utf8');
const provinceSelect=mainHtml.match(/<select id="province">([\s\S]*?)<\/select>/)[1];
const provinceOptions=[...provinceSelect.matchAll(/<option(?: [^>]*)?>([^<]*)<\/option>/g)].map(m=>m[1]);
assert.deepEqual(provinceOptions,['Not confirmed','ON','BC','AB','SK','MB','NB','NS','PE','NL','QC','YT','NT','NU']);
console.log('Exact precision boundary, inherited year-key and usable province-option regressions passed.');
}


assert.notEqual(C.normal("O'NEIL"),C.normal('O NEIL'));
assert.equal(C.detect('Unrelated invoice','T4 2025.pdf'),'Unknown');
assert.equal(A.redact({sha256:'a123456789'+'f'.repeat(54)}).sha256,'a123456789'+'f'.repeat(54));
assert.equal(L.locateFinding(navigationDoc,{title:'General review'},NaN).page,0);
